<?php


/**
 * add e-Edition link to user menu
 * @return array
 */
function etype_xml_importer_menu() {

  $items = array();

  $items['import_olive_xml'] = array(
    'title' => 'Import Olive XML',
    'description' => 'Olive XML Importer',
    'page callback' => 'etype_xml_importer_olive_import',
    'access arguments' => array('access administration pages'),
    'menu_name' => 'user-menu',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/xml_importer.import.inc'
  );

  $items['import_etype_xml'] = array(
    'title' => 'Import eType XML',
    'description' => 'eType XML Importer',
    'page callback' => 'etype_xml_importer_etype_import',
    'access arguments' => array('access administration pages'),
    'menu_name' => 'user-menu',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/xml_importer.import.inc'
  );

  return $items;
}
