<?php

/**
 * Implements hook_block_info().
 */
function etype_block_info() {
  $blocks = array();
  $blocks['Social'] = array(
    'info' => t('Social'),
  );
  $blocks['Facebook'] = array(
    'info' => t('Facebook'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function etype_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'Social':
      $block['subject'] = 'Follow Us';
      $block['content'] = _etype_social_content();
      break;

    case 'Facebook':
      $block['subject'] = 'Facebook';
      $block['content'] = _etype_facebook_content();
      break;
  }
  return $block;
}

/**
 * Social Block
 * @return null
 */
function _etype_social_content() {
  $output = '';
  $facebook = theme_get_setting('facebook','cni');
  $twitter = theme_get_setting('twitter','cni');
  $pinterest = theme_get_setting('pinterest','cni');
  if ( ! empty($facebook)) {
    $output .= '<div class="facebook"><a href="' . $facebook . '">Like us on Facebook</a></div>';
  }
  if ( ! empty($twitter)) {
    $output .= '<div class="twitter"><a href="' . $twitter . '">Follow us on Twitter</a></div>';
  }
  if ( ! empty($pinterest)) {
    $output .= '<div class="pinterest"><a href="' . $pinterest . '">Follow us on Pinterest</a></div>';
  }
  return $output;
}

function _etype_facebook_content() {
  $output = '';
  $facebook = theme_get_setting('facebook','cni');

  if ( ! empty($facebook)) {
    $output .= '
 <div class="fb-page" data-href="' . $facebook . '" data-tabs="timeline" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>
    ';
  }

  return $output;
}