<?php

/**
 * Implements hook_block_info().
 */
function etype_block_info() {
  $blocks = array();

  $blocks['Social'] = array(
    'info' => t('Social'),
  );

  $blocks['Facebook'] = array(
    'info' => t('Facebook'),
  );

  $blocks['Twitter'] = array(
    'info' => t('Twitter'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function etype_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'Social':
      $block['subject'] = 'Follow Us';
      $block['content'] = _etype_social_content();
      break;

    case 'Facebook':
      $block['subject'] = 'Facebook';
      $block['content'] = _etype_facebook_content();
      break;

    case 'Twitter':
      $block['subject'] = 'Twitter';
      $block['content'] = _etype_twitter_content();
      break;
  }
  return $block;
}

/**
 * Social Block
 * @return null
 */
function _etype_social_content() {
  $output = '';
  $facebook = theme_get_setting('facebook','cni');
  $twitter = theme_get_setting('twitter','cni');
  $pinterest = theme_get_setting('pinterest','cni');
  if ( ! empty($facebook)) {
    $output .= '<div class="facebook"><a href="https://www.facebook.com/' . $facebook . '">Like us on Facebook</a></div>';
  }
  if ( ! empty($twitter)) {
    $output .= '<div class="twitter"><a href="https://twitter.com/' . $twitter . '">Follow us on Twitter</a></div>';
  }
  if ( ! empty($pinterest)) {
    $output .= '<div class="pinterest"><a href="https://www.pinterest.com/' . $pinterest . '">Follow us on Pinterest</a></div>';
  }
  return $output;
}

/**
 * @return string
 */
function _etype_facebook_content() {
  $output = '';
  $facebook = theme_get_setting('facebook','cni');

  if ( ! empty($facebook)) {
    $output .= '
 <div class="fb-page" data-href="https://www.facebook.com/' . $facebook . '" data-tabs="timeline" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>
    ';
  }

  return $output;
}

/**
 * @return string
 */
function _etype_twitter_content() {
  $output = '';
  $twitter = theme_get_setting('twitter','cni');
  $twitter_widget_id = theme_get_setting('twitter_widget_id','cni');

  if ( ! empty($twitter)) {
    $output .= '
<a class="twitter-timeline" href="https://twitter.com/' . $twitter . '" data-widget-id="' . $twitter_widget_id . '">Tweets by @' . $twitter . '</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    ';
  }

  return $output;
}