<?php
/**
 * Implements hook_block_info()
 */
function etype_sliderad_block_info() {
  $blocks = array();

  $blocks['Slider Ad'] = array(
    'info' => t('Slider Ad'),
  );

  return $blocks;

}

/**
 * @param string $delta
 * @return array
 * Implements hook_block_view()
 */
function etype_sliderad_block_view($delta = '') {
  $block = array();
  switch ($delta) {

    case 'Slider Ad':
      $block['subject'] = '';
      $block['content'] = etype_sliderad_content();
      break;
  }

  return $block;
}

/**
 *
 */
function etype_sliderad_content() {

  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'sliderad')
    ->execute();
  $nodes = node_load_multiple(array_keys($result['node']));

  // print_r($nodes);

  $output = "<p>Slider Ad</p>";
  return $output;
}