<?php
/**
 * Implements hook_block_info()
 */
function etype_sliderad_block_info() {
  $blocks = array();

  $blocks['Slider Ad'] = array(
    'info' => t('Slider Ad'),
  );

}

/**
 * @param string $delta
 * @return array
 * Implements hook_block_view()
 */
function etype_sliderad_block_view($delta = '') {
  $block = array();
  switch ($delta) {

    case 'Slider Ad':
      $block['subject'] = '';
      $block['content'] = 'Add here';
      break;
  }

  return $block;
}